- name: create lita app config directory
  file: >
    path=~/apps/{{ lita_app_name }}/shared/config
    state=directory
    owner={{ deploy_user }}
    group={{ deploy_user }}
    recurse=yes

- name: check for log directory
  stat: path=~/apps/{{ lita_app_name }}/shared/log
  register: log_dir

- name: create lita app log directory (only if one is not there)
  file: >
    path=~/apps/{{ lita_app_name }}/shared/log
    state=directory
    owner={{ deploy_user }}
    group={{ deploy_user }}
    recurse=yes
  when: >
    log_dir.stat.isdir is defined and log_dir.stat.isdir

- name: install lita application.yml
  template: src=templates/application.yml dest=~/apps/{{ lita_app_name }}/shared/config/application.yml

- name: check for current directory
  stat: path=~/apps/{{ lita_app_name }}/current
  register: currnet_dir

- name: create lita app current directory (only if one is not there)
  file: >
    path=~/apps/{{ lita_app_name }}/current
    state=directory
    owner={{ deploy_user }}
    group={{ deploy_user }}
    recurse=yes
  when: >
    currnet_dir.stat.isdir is defined and currnet_dir.stat.isdir