- hosts: all
  sudo: yes
  tasks:
    - include: tasks/setup.yml
    - include: tasks/environment-variables.yml

- hosts: all
  sudo: yes
  sudo_user: "{{ deploy_user }}"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/lita-config.yml

- hosts: all
  sudo: yes
  tasks:
    - include: tasks/ufw.yml

- hosts: all
  sudo: yes
  sudo_user: "{{ deploy_user }}"
  tasks:
    - include: tasks/rbenv.yml
  handlers:
    #- include: handlers/rbenv.yml
    - name: update .profile
      lineinfile:
        dest: ~/.profile
        line: '{{item.line}}'
        regexp: '{{item.regexp}}'
      with_items:
        - line: export PATH="$HOME/.rbenv/bin:$PATH"
          regexp: PATH.*rbenv
        - line: eval "$(rbenv init -)"
          regexp: rbenv.*init

- hosts: all
  sudo: yes
  tasks:
    - include: tasks/rbenv-ruby.yml

- hosts: all
  sudo: yes
  tasks:
    - include: tasks/redis.yml
  handlers:
    #- include: handlers/redis.yml
    - name: restart redis-server
      service: name=redis-server state=restarted

# - hosts: all
#   sudo: yes
#   tasks:
#     - include: tasks/upstart.yml

- hosts: all
  sudo: no
  tasks:
    - include: tasks/lita_deployment.yml

